---
- name: Get Show Counters for Jericho 7280SR-48Y6
  hosts: arista
  gather_facts: False

  tasks:
    - name: Check if file needs to be created
      local_action: stat path=./{{ inventory_hostname }}cpucounters
      register: doesfileexist
    - name: Create file if needed
      file:
        path: "./{{ inventory_hostname }}cpucounters"
        state: touch
        mode: 0755
      when: doesfileexist.stat.exists == false
    - name: Gather Show CPU Counters
      eos_command:
        commands:
        - command: show cpu counters queue
          output: json
      register: cpu_counters
    - name: Populate Variables
      set_fact:
          bytesJericho00: "droppedBytes: {{ cpu_counters.stdout_lines[0]['ingressVoqs']['sources']['Jericho0.0']['cpuClasses']['CoppSystemVxlanEncap']['ports']['']['droppedBytes'] }}"
          bytesJericho01: "droppedBytes: {{ cpu_counters.stdout_lines[0]['ingressVoqs']['sources']['Jericho0.1']['cpuClasses']['CoppSystemVxlanEncap']['ports']['']['droppedBytes'] }}"
    - name: Display Current Show CPU Counters Dropped Bytes
      debug:
        msg: 
          - "{{ bytesJericho00 }}"
          - "{{ packetsJericho00 }}"
          - "{{ bytesJericho01 }}"
          - "{{ packetsJericho01 }}"
          - "{{ lookup('pipe','date') }}"
    - name: Send Jericho0.0 to files
      local_action: lineinfile line="{{ lookup('pipe','date') }} 'Jericho00-CoppSystemVxlanEncap' {{ bytesJericho00 }} {{ packetsJericho00 }}" insertafter=EOF dest=./{{ inventory_hostname }}cpucounters
    - name: Send Jericho0.1 to files
      local_action: lineinfile line="{{ lookup('pipe','date') }} 'Jericho01-CoppSystemVxlanEncap' {{ bytesJericho01 }} {{ packetsJericho01 }}" insertafter=EOF dest=./{{ inventory_hostname }}cpucounters

